### ISSUE TITLE
Add a reset button when game is running

### ISSUE THREAD

**Issue by sadn1ck** [arnabsen1729/Puzzle-Game#1]
A reset button which resets counter and moves so failures at this game like me can restart the game without reloading the page.

**Comment by arnabsen1729** [comment]
Then maybe I won't disable the Scramble button, because all it does is make the counter zero, and scramble again. Also it is a pretty easy game -_-

**Comment by sadn1ck** [comment]
Or you could have it say **reset** in the gameloop. :D
